# Site settings
title: The Coding Rabbi
header-img: img/home-bg.png
email: bengreenberg@gmail.com
copyright_name: benhayehudi
description: > # this means to ignore newlines until "baseurl:"
  From Talmud to Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: RabbiGreenberg
github_username:  benhayehudi
learn_profile: benhayehudi
email_username: bengreenberg@gmail.com
site_author: Ben Greenberg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-feed

gems: [jekyll-paginate, jekyll-feed]
